### PR TITLE
Wrap NetHome Plus login with a semaphore

### PR DESCRIPTION
**Pull request by dkerr64**
With luck this will fix the problem in issue #10.

### CODE REVIEW

**Review by kovapatrik — APPROVED** [review]

**Comment by dkerr64** [comment]
We'll need to bump version number before publishing to NPM so that Homebridge recognizes that there is an update.

**Comment by kovapatrik** [comment]
Yeah, that's why I didn't merged it yet, but I'm on my phone right now so I can't bump it.

**Comment by dkerr64** [comment]
I just did it.

**Comment by dkerr64** [comment]
I was worried when I saw that you had added a workflow to automatically publish when code pushed to main, I had not registered that before I opened the PR.  Demands extra care to make sure everything is in order!

**Comment by kovapatrik** [comment]
True, but that's what reviews are for. Worst case, if I didn't catch if there is a bump or not, there will be a build error and I have to push a bump commit to main.

**Pull request merged**
