### PR TITLE
fix: error to warning

### PR DESCRIPTION
**Pull request by kovapatrik**
I have replaced some error to warnings, as they are "handled" errors.

@dkerr64 I've also added a TODO when the unsupported protocols being handled. I've commented out the handling because in some cases the message was compatible with my device but there were a connection error while reading from the device with caused the command being marked as "unsupported".

### CODE REVIEW

**Comment by dkerr64** [comment]
We should "upgrade" the debug-level log [here](https://github.com/dkerr64/homebridge-midea-platform/blob/e763022ecb22db15a4b42a3d8610ec47a9808566/src/core/MideaDevice.ts#L437) to a info-level.

**Comment by dkerr64** [comment]
If we want to "silently" handle network errors / reconnects then we could wrap [this](https://github.com/kovapatrik/homebridge-midea-platform/blob/c309c5fd219ec67d17f23c9b04addd062788e8eb/src/core/MideaDevice.ts#L492) in a test for verbose and downgrade it to a warning from an error.  If we change the debug to info in the reconnect code  like I suggest above then that would appear in the log and be less alarming to users.

**Comment by kovapatrik** [comment]
I've added the things you mentioned.

**Review by dkerr64 — APPROVED** [review]
Looks good.

**Pull request merged**
