### PR TITLE
Show discovery progress messages (toast popups)

### PR DESCRIPTION
**Pull request by dkerr64**
What do you think of this?  I would like to provide some user feedback during the discovery process and so tested using the custom IU postEvent method.  It works pretty well.

Right now it just shows discovery start/complete and each device found.  But ideally I would like to provide a message each time the broadcast "retries" so that every couple of seconds the user gets reassurance that things are working.  I will have to provide a mechanism for MideaDiscover to callback for that though, so wanted to get your thoughts before going further.

Thanks.

### CODE REVIEW

**Comment by dkerr64** [comment]
Realized that adding retry messages was easy, so I did it.  Looks really good to me.  Your thoughts?

**Comment by kovapatrik** [comment]
I like it, but I think it's a bit much. A popup when discovery starts and ends would be enough in my opinion.

**Comment by kovapatrik** [comment]
Or I don't know...if someone has many devices it can fill the entire screen I think:D

**Comment by dkerr64** [comment]
Good point about lots of devices.  I would remove the notification of device found and leave in the every-two-seconds pulse (maybe with count of devices discovered)

it is the 2-second pulse I like most because it is reassurance that things are still working and not hung.

**Comment by kovapatrik** [comment]
Good idea!

**Comment by dkerr64** [comment]
I’m out right now.  Will make the change later today.

**Comment by dkerr64** [comment]
I think it is good now.  Can merge if you are happy with it.

**Review by kovapatrik — APPROVED** [review]

**Pull request merged**
